# postgres/pmapp user/password credentials
version: '3.7'


networks:
  app-tier:
    driver: bridge


services:
  db:
    image: postgres
    networks:
      - app-tier
    restart: always
    environment:
      POSTGRES_PASSWORD: pmapp
      POSTGRES_USER: postgres
      POSTGRES_DB: pmapp
    ports:
      - 5432:5432

  be:
    image: ricardo/pmapp-be
    networks:
      - app-tier
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      WAIT_HOSTS: db:5432    

  adminer:
    image: adminer
    networks:
      - app-tier
    restart: always
    ports:
      - 9000:8080